### ISSUE TITLE
Do we want to offer an RSS Feed?

### ISSUE THREAD

**Issue by kkmann** [RConsortium/asa-biop-swe-wg#17]
Would we want to offer an RSS feed or even email subscriptions? 

RSS: https://quarto.org/docs/websites/website-blog.html#rss-feed

email: https://quarto.org/docs/websites/website-blog.html#subscriptions, maybe via free mailchimp? https://mailchimp.com/de/pricing/marketing/?currency=EUR or alternatives https://themeisle.com/blog/best-free-email-marketing-services/

**Comment by ellessenne** [comment]
I think we should definitely have _at least_ an RSS feed, especially since it seems straightforward with Quarto!

**Comment by danielinteractive** [comment]
Thanks @kkmann , I think @vitallish volunteered to drive this forward

**Comment by vitallish** [comment]
I made some small changes to the side that allow for RSS readers to pull in information along with a little RSS icon in the upper right hand corner. 

I also limited the RSS feed to just the posts in the [news] category. This is what it looks like in a reader:
![image](https://user-images.githubusercontent.com/4785053/203642091-1a8e36dc-0e80-4df3-98b5-66599d09350d.png)

There is also an overall RSS feed for the whole site created at the same time but it looks a bit cluttered I think - I figure people would just care about the 'news' items. We will need to merge this in and get the RSS feed working before setting up any subscription services - they require an existing RSS feed that isn't on my local computer.

**Comment by danielinteractive** [comment]
Thanks @vitallish ! Actually we can restrict it to the blog I think. Moving forward I think almost all news items will anyway be blog entries

**Comment by danielinteractive** [comment]
thanks @vitallish - one question, is it normal that when clicking on 
<img width="92" alt="image" src="https://user-images.githubusercontent.com/1071227/203730319-50b2f0a7-7970-4b64-b1bd-31af451e899e.png">
I just get
<img width="912" alt="image" src="https://user-images.githubusercontent.com/1071227/203730359-3bb0ca0b-e937-4e40-a888-e88b900deae5.png">
?

**Comment by vitallish** [comment]
Yes I believe that's correct - you usually just copy that link and add it to the RSS program of your choice - for example feedly.com or Net News Wire (for macs). Some browsers have them built in as well.
