### ISSUE TITLE
Add hex wall page

### ISSUE THREAD

**Issue by danielinteractive** [RConsortium/asa-biop-swe-wg#86]
Inspiration:
- repo is at https://github.com/pharmaverse/pharmaverse 
- packages are listed at https://github.com/pharmaverse/pharmaverse/tree/main/data/packages 
- script for producing the hexwall is at https://github.com/pharmaverse/pharmaverse/blob/main/scripts/hexwall.R 

Scope:
- to include not just our own packages, but clinical trial task view packages (https://cran.r-project.org/web/views/ClinicalTrials.html)
- also need to standardize the format of the hex stickers

**Comment by danielinteractive** [comment]
It looks pretty nice now at https://www.openstatsware.org/hexwall.html thanks @yonicd !

Minor things still to do:
- [ ] Avoid the `NA` package message in the beginning when landing on the page, if possible
- [ ] Include the hexwall page in one of the page tabs so users can find it 
- [ ] I think a blog entry for this would be appropriate too since it is a cool new feature!

**Comment by yonicd** [comment]
I am not sure why the existing hex stickers are not being fetched. is there a connectivity problem? or a missing GH token for the runner?

**Comment by danielinteractive** [comment]
Which ones are not fetched? I did not spot that , just had the other comments

**Comment by yonicd** [comment]
there are no original hex stickers on the wall. that indicates it had a problem fetching them.

**Comment by danielinteractive** [comment]
Also the deployment log looks ok:
![image](https://github.com/RConsortium/asa-biop-swe-wg/assets/1071227/ed97f5d9-3fd1-4e81-94a3-e2ea570b6f3d)
Maybe we could try to add some kind of log messages into the `hexwall` code to see what is going on during the GHA?

**Comment by yonicd** [comment]
missing GHA PAT in the runner: https://github.com/RConsortium/asa-biop-swe-wg/actions/runs/7935390913/job/21668415248#step:6:107

**Comment by danielinteractive** [comment]
Ah so how do we add that missing PAT?

**Comment by danielinteractive** [comment]
Thanks @yonicd for the GHA work, now I can see the hex stickers on the wall!

Can you also have a look at the remaining 2 tasks above?
