### ISSUE TITLE
Get rid of the security warning on openstatsware.org

### ISSUE THREAD

**Issue by danielinteractive** [RConsortium/asa-biop-swe-wg#90]
How can we get rid of the security warning? (exclamation mark in triangle icon)
![image](https://github.com/RConsortium/asa-biop-swe-wg/assets/1071227/fac8e9d2-43a1-4625-9b8b-03a2a5b807ab)

**Comment by ellessenne** [comment]
I think there is a tick box in "Settings/Pages" to enforce HTTPS – could you check that @danielinteractive?

It might be necessary to generate a certificate when using a custom domain (or verify the domain first), but should be all straightforward – more infos [here](https://docs.github.com/en/pages/getting-started-with-github-pages/securing-your-github-pages-site-with-https) and [here](https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/verifying-your-custom-domain-for-github-pages).

**Comment by danielinteractive** [comment]
Thanks @ellessenne , @vitallish can you check this out for us? Thanks :)

**Comment by vitallish** [comment]
I agree that enforce HTTPS needs to set. If the domain is properly is properly verified then we should be set. @danielinteractive I'm happy to play around with this but I'd need to be an admin for the repo.

**Comment by vitallish** [comment]
if that doesn't work then there is some verification that needs to happen - I created a branch to mimic what I have done before - I can open a PR if needed.

**Comment by danielinteractive** [comment]
@vitallish great, I gave you admin access now so you can have a look - the https enforce option is set but I think we need to do more to register the custom domain with GitHub pages.

**Comment by danielinteractive** [comment]
So I merged the CNAME thing, but now this happens:

![image](https://github.com/RConsortium/asa-biop-swe-wg/assets/1071227/0957998b-97a8-4a00-8016-124753fab4fe)

and both links are no longer available (too many redirects).
I guess we now need to change the configuration of openstatsware.org - previously it used to redirect to https://rconsortium.github.io/asa-biop-swe-wg but now it should not do that anymore?

**Comment by danielinteractive** [comment]
OK for now let's roll back the PR so that the site is online and then we can revisit this in January.

**Comment by vitallish** [comment]
Yes I agree, (I was nervous to play around with this because I didn't have
access to the the openstatsware name)

**Comment by ellessenne** [comment]
@danielinteractive is the old URL redirected from the domain registrar?

**Comment by danielinteractive** [comment]
@ellessenne , yep, at the moment openstatsware.org redirects to rconsortium.github.io/asa-biop-swe-wg
I guess we would need to change that then - but I don't personally have the admin rights for that so let's better wait until January when I can liaise with admin

**Comment by ellessenne** [comment]
Yeah, I agree, I think that's best for now – this is much easier to debug/fix having admin access to both this repo and the domain dashboard 😄

**Comment by ellessenne** [comment]
Now fixed.
